# Generated by cpp11: do not edit by hand

numeric_along_interpolator <- function(data, group, time, history, keep_last, frames, ease) {
  .Call("_tweenr_numeric_along_interpolator", data, group, time, history, keep_last, frames, ease, PACKAGE = "tweenr")
}

colour_along_interpolator <- function(data, group, time, history, keep_last, frames, ease) {
  .Call("_tweenr_colour_along_interpolator", data, group, time, history, keep_last, frames, ease, PACKAGE = "tweenr")
}

constant_along_interpolator <- function(data, group, time, history, keep_last, frames, ease) {
  .Call("_tweenr_constant_along_interpolator", data, group, time, history, keep_last, frames, ease, PACKAGE = "tweenr")
}

list_along_interpolator <- function(data, group, time, history, keep_last, frames, ease) {
  .Call("_tweenr_list_along_interpolator", data, group, time, history, keep_last, frames, ease, PACKAGE = "tweenr")
}

numlist_along_interpolator <- function(data, group, time, history, keep_last, frames, ease) {
  .Call("_tweenr_numlist_along_interpolator", data, group, time, history, keep_last, frames, ease, PACKAGE = "tweenr")
}

phase_along_interpolator <- function(group, time, history, keep_last, frames) {
  .Call("_tweenr_phase_along_interpolator", group, time, history, keep_last, frames, PACKAGE = "tweenr")
}

numeric_at_interpolator <- function(from, to, at, ease) {
  .Call("_tweenr_numeric_at_interpolator", from, to, at, ease, PACKAGE = "tweenr")
}

colour_at_interpolator <- function(from, to, at, ease) {
  .Call("_tweenr_colour_at_interpolator", from, to, at, ease, PACKAGE = "tweenr")
}

constant_at_interpolator <- function(from, to, at, ease) {
  .Call("_tweenr_constant_at_interpolator", from, to, at, ease, PACKAGE = "tweenr")
}

list_at_interpolator <- function(from, to, at, ease) {
  .Call("_tweenr_list_at_interpolator", from, to, at, ease, PACKAGE = "tweenr")
}

numlist_at_interpolator <- function(from, to, at, ease) {
  .Call("_tweenr_numlist_at_interpolator", from, to, at, ease, PACKAGE = "tweenr")
}

numeric_element_interpolator <- function(data, group, frame, ease) {
  .Call("_tweenr_numeric_element_interpolator", data, group, frame, ease, PACKAGE = "tweenr")
}

colour_element_interpolator <- function(data, group, frame, ease) {
  .Call("_tweenr_colour_element_interpolator", data, group, frame, ease, PACKAGE = "tweenr")
}

constant_element_interpolator <- function(data, group, frame, ease) {
  .Call("_tweenr_constant_element_interpolator", data, group, frame, ease, PACKAGE = "tweenr")
}

list_element_interpolator <- function(data, group, frame, ease) {
  .Call("_tweenr_list_element_interpolator", data, group, frame, ease, PACKAGE = "tweenr")
}

numlist_element_interpolator <- function(data, group, frame, ease) {
  .Call("_tweenr_numlist_element_interpolator", data, group, frame, ease, PACKAGE = "tweenr")
}

phase_element_interpolator <- function(data, group, frame, ease) {
  .Call("_tweenr_phase_element_interpolator", data, group, frame, ease, PACKAGE = "tweenr")
}

numeric_element_at_interpolator <- function(data, group, time, at, ease) {
  .Call("_tweenr_numeric_element_at_interpolator", data, group, time, at, ease, PACKAGE = "tweenr")
}

colour_element_at_interpolator <- function(data, group, time, at, ease) {
  .Call("_tweenr_colour_element_at_interpolator", data, group, time, at, ease, PACKAGE = "tweenr")
}

constant_element_at_interpolator <- function(data, group, time, at, ease) {
  .Call("_tweenr_constant_element_at_interpolator", data, group, time, at, ease, PACKAGE = "tweenr")
}

list_element_at_interpolator <- function(data, group, time, at, ease) {
  .Call("_tweenr_list_element_at_interpolator", data, group, time, at, ease, PACKAGE = "tweenr")
}

numlist_element_at_interpolator <- function(data, group, time, at, ease) {
  .Call("_tweenr_numlist_element_at_interpolator", data, group, time, at, ease, PACKAGE = "tweenr")
}

phase_element_at_interpolator <- function(data, group, time, at, ease) {
  .Call("_tweenr_phase_element_at_interpolator", data, group, time, at, ease, PACKAGE = "tweenr")
}

numeric_fill_interpolator <- function(data, ease) {
  .Call("_tweenr_numeric_fill_interpolator", data, ease, PACKAGE = "tweenr")
}

colour_fill_interpolator <- function(data, ease) {
  .Call("_tweenr_colour_fill_interpolator", data, ease, PACKAGE = "tweenr")
}

constant_fill_interpolator <- function(data, ease) {
  .Call("_tweenr_constant_fill_interpolator", data, ease, PACKAGE = "tweenr")
}

list_fill_interpolator <- function(data, ease) {
  .Call("_tweenr_list_fill_interpolator", data, ease, PACKAGE = "tweenr")
}

numlist_fill_interpolator <- function(data, ease) {
  .Call("_tweenr_numlist_fill_interpolator", data, ease, PACKAGE = "tweenr")
}

numeric_state_interpolator <- function(data, states) {
  .Call("_tweenr_numeric_state_interpolator", data, states, PACKAGE = "tweenr")
}

colour_state_interpolator <- function(data, states) {
  .Call("_tweenr_colour_state_interpolator", data, states, PACKAGE = "tweenr")
}

constant_state_interpolator <- function(data, states) {
  .Call("_tweenr_constant_state_interpolator", data, states, PACKAGE = "tweenr")
}

list_state_interpolator <- function(data, states) {
  .Call("_tweenr_list_state_interpolator", data, states, PACKAGE = "tweenr")
}

numlist_state_interpolator <- function(data, states) {
  .Call("_tweenr_numlist_state_interpolator", data, states, PACKAGE = "tweenr")
}

phase_state_interpolator <- function(data, states) {
  .Call("_tweenr_phase_state_interpolator", data, states, PACKAGE = "tweenr")
}
