# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

numeric_interpolator <- function(data, states) {
    .Call('tweenr_numeric_interpolator', PACKAGE = 'tweenr', data, states)
}

colour_interpolator <- function(data, states) {
    .Call('tweenr_colour_interpolator', PACKAGE = 'tweenr', data, states)
}

constant_interpolator <- function(data, states) {
    .Call('tweenr_constant_interpolator', PACKAGE = 'tweenr', data, states)
}

