# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

numeric_state_interpolator <- function(data, states) {
    .Call('_tweenr_numeric_state_interpolator', PACKAGE = 'tweenr', data, states)
}

colour_state_interpolator <- function(data, states) {
    .Call('_tweenr_colour_state_interpolator', PACKAGE = 'tweenr', data, states)
}

constant_state_interpolator <- function(data, states) {
    .Call('_tweenr_constant_state_interpolator', PACKAGE = 'tweenr', data, states)
}

list_state_interpolator <- function(data, states) {
    .Call('_tweenr_list_state_interpolator', PACKAGE = 'tweenr', data, states)
}

numlist_state_interpolator <- function(data, states) {
    .Call('_tweenr_numlist_state_interpolator', PACKAGE = 'tweenr', data, states)
}

phase_state_interpolator <- function(data, states) {
    .Call('_tweenr_phase_state_interpolator', PACKAGE = 'tweenr', data, states)
}

numeric_element_interpolator <- function(data, group, frame, ease) {
    .Call('_tweenr_numeric_element_interpolator', PACKAGE = 'tweenr', data, group, frame, ease)
}

colour_element_interpolator <- function(data, group, frame, ease) {
    .Call('_tweenr_colour_element_interpolator', PACKAGE = 'tweenr', data, group, frame, ease)
}

constant_element_interpolator <- function(data, group, frame, ease) {
    .Call('_tweenr_constant_element_interpolator', PACKAGE = 'tweenr', data, group, frame, ease)
}

list_element_interpolator <- function(data, group, frame, ease) {
    .Call('_tweenr_list_element_interpolator', PACKAGE = 'tweenr', data, group, frame, ease)
}

numlist_element_interpolator <- function(data, group, frame, ease) {
    .Call('_tweenr_numlist_element_interpolator', PACKAGE = 'tweenr', data, group, frame, ease)
}

phase_element_interpolator <- function(data, group, frame, ease) {
    .Call('_tweenr_phase_element_interpolator', PACKAGE = 'tweenr', data, group, frame, ease)
}

